### ISSUE TITLE
List hex & RGB values of each color in README

### ISSUE THREAD

**Issue by iandwelker** [rose-pine/rose-pine-theme#10]
First off, this theme looks really nice and I love the colors. 

I was actually hoping to port this to a vim theme, but there doesn't seem to be an easily-accessible document that lists all the hex and rgb values of each of the colors in the theme. I can poke around in one of the linked repositories that contains program config files, but I'm not always certain where the colors are listed in that repo, sometimes they're specified in a format that I don't quite understand, and (as far as I can tell) not each linked repository uses all of the colors, so it's not the easiest to port this to a new application. 

I feel it would be much easier to port this to a new application if you explicitly listed each of the color's hex and rgb values directly on the README (or another easily-accessible document in this main repo), alongside the color which it corresponds to. Would it be possible to do that?

**Comment by ThatOneCalculator** [comment]
Sounds like a great idea! I'll add those in ASAP :)

**Comment by mvllow** [comment]
Thank you for the suggestion! A list of colours can now be found at https://mellow.dev/rose-pine. The other variants will be added once we have those 100% figured out.

Good luck and please reach out if you have any questions 🥰
