### ISSUE TITLE
Better theme request for Emacs

### ISSUE THREAD

**Issue by shuriken1812** [rose-pine/rose-pine-theme#100]
### Link to app

https://www.gnu.org/software/emacs/

### Would you be willing to work on this?

- [ ] Sure

### What is your favourite Rosé Pine accent

None

### Additional information

The current rose pine emacs implementation is incomplete and does not follow the entire color palette.

You can easily compare the screenshots from 

https://github.com/thongpv87/rose-pine-emacs
https://github.com/rose-pine/vscode
https://github.com/rose-pine/neovim

And see the issue.. 

https://github.com/thongpv87/rose-pine-emacs/blob/master/rose-pine-color-theme.el

Rose Pine implementation here for example only using `faded` `love` `iris` for most of the things.. making things look only pinkish-white. As compared to the implementations taking advantage of the full color palette as it is supposed to. Colors like Pine and foam are not even used and key values like func/local are also shown in `love` instead of `pine`.
Other colors like foam for function names and gold are also not even used.... It only uses few colors from the palette and does not even come close to the other implementations. The last update was 3 years ago and doesn't seem to be well maintained.

That said.. I am aware all these are community maintained and with no disrespect to the original author.. I think the emacs theme can be reworked.. Great work defining the color palette.

**Comment by mvllow** [comment]
Happy to accept a more complete theme into our org.

A few questions for you or anyone else interested:

1. What are some well made themes for emacs to reference?

2. Is Doom Emacs or something similar a good out of box experience for someone not familiar with emacs to create a theme?

Ideally someone who is more experienced with emacs would want to contribute this but I wouldn't mind attempting it if not :)

**Comment by shuriken1812** [comment]
> Happy to accept a more complete theme into our org.
> 
> A few questions for you or anyone else interested:
> 
> 1. What are some well made themes for emacs to reference?
> 2. Is Doom Emacs or something similar a good out of box experience for someone not familiar with emacs to create a theme?
> 
> Ideally someone who is more experienced with emacs would want to contribute this but I wouldn't mind attempting it if not :)

Sure I can help u along.. 

1 - There are many well made themes for emacs..keeping all the subjective  side aside.. what makes a good theme is which is able to understand LSP.. has different color for key.. variable.. etc.. and uses the colors from color palette optimally.

Some examples that will help keeping subjective cases aside again would be - 
https://github.com/doomemacs/themes/blob/master/themes/doom-tomorrow-night-theme.el

- clearly distinguished functions.. methods.. variable declaration.. strings etc... and follows and uses the color palette as intended.

Some themes rely on autothemer package. a example and the theme I use currently, this also clearly defines variables from the color palette of the original kanagawa neovim theme and makes full use of them -
https://github.com/konrad1977/emacs/blob/main/themes/kanagawa-theme.el


2 - Yes doom emacs makes OOTP experience really great some key things that someone new would appreciate - 

- uses vim keybindings by default (evil keybindings).
- A good video to clearly get started by distrotube https://www.youtube.com/watch?v=37H7bD-G7nE
- a simple `init.el` file to simply uncomment what you need for example for `rust + lsp` support you simply uncomment tools lsp and rust +lsp in the `init.el` file.. 
- uses its own way to install packages - In `packages.el` you can simply specify the packages you want to use.
- Doesn't make user touch emacs.d folder and user can do everything in doom.d folder which lets self maintained stuff to be really organized.

**Comment by shuriken1812** [comment]
Regarding the theme I might be able to work on it but for my level of knowledge I would need to research a bit just to get right colors at the right place.

**Comment by shuriken1812** [comment]
Here we have a great theme by https://github.com/konrad1977/pinerose-emacs/blob/main/rose-pine-theme.el @konrad1977 :) great implementation

**Comment by shuriken1812** [comment]
Here is a simple rust example using the above mentioned theme

![Screenshot from 2023-04-10 06-59-06](https://user-images.githubusercontent.com/40650341/230807747-15e77dfb-3b84-4c60-b3cc-a3627cbd0187.png)

**Comment by mvllow** [comment]
I have added the above theme to our new site which should be live in the next week or two. Thank you :)

**Comment by konrad1977** [comment]
@mvllow Let me know If I need to update something, like copy right notice or colors.

**Comment by emilknievel** [comment]
@konrad1977 Been looking for a good version of this theme for Emacs, I really like what you've done with it :)

Any plans on implementing the different variants of this theme?

**Comment by konrad1977** [comment]
I could do that :)

**Comment by mvllow** [comment]
Closing since this is live on the website, thank you for the theme :)
