### ISSUE TITLE
New theme for fcitx5

### ISSUE THREAD

**Issue by scotabroad** [rose-pine/rose-pine-theme#101]
### Link to theme repo

https://github.com/scotabroad/fcitx5

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

I have made a theme for the fcitx5 input engine... legacy fcitx is still around so is it alright if I keep the number 5 in the repo name to help disambiguate which version of fcitx the theme is compatible with?

**Comment by mvllow** [comment]
Thanks for the contribution :)

As far as naming, if it makes sense to have a general "fcitx" repo with a "fcitx5" folder or similar, e.g. our gtk repo having gtk3 and gtk4 folder, then I'd recommend that route. If it doesn't make sense to have multiple versions supported in the future then "fcitx5" repo name is fine.

**Comment by scotabroad** [comment]
No problem! I don't think keeping both in the same repo is a good idea given that fcitx and fcitx5 are mutually exclusive, and the former is only maintained for security fixes, so I'm just gonna keep the repo with having the same name.
