### ISSUE TITLE
New theme for urxvt

### ISSUE THREAD

**Issue by SarahAllenReed** [rose-pine/rose-pine-theme#104]
### Link to theme repo

https://github.com/SarahAllenReed/rose-pine-urxvt

### What would you like to do with your repo?

Duplicate (clone) my repo into the org

### Additional information

This could also be used as a standard .Xresources template for anything that uses Xresources for color palletes.

**Comment by ThatOneCalculator** [comment]
We already have an XResources repo https://github.com/rose-pine/xresources

**Comment by SarahAllenReed** [comment]
That's on me, then. I checked on the website and it wasn't there, so I made one without realizing it was a duplicate. 

![image](https://user-images.githubusercontent.com/8343978/232075250-960c778a-284c-43e7-99b8-77c4ce7c2e35.png)

Don't suppose you also have a qt5 theme? I also ended up porting the theme there. Don't want to keep troubling you all with duplicate commits.

**Comment by mvllow** [comment]
> That's on me, then. I checked on the website and it wasn't there, so I made one without realizing it was a duplicate. 
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/8343978/232075250-960c778a-284c-43e7-99b8-77c4ce7c2e35.png)

Shoot, apologies for that. I'll add that to the site today :)

Doesn't look like our theme has screenshots but if you wanted to PR your screenshots and add your name under the "Thanks to" section that'd be lovely 💜

**Comment by SarahAllenReed** [comment]
Can do. You mean screenshots for the urxvt/Xresources theme or the qt5 theme I'm working on?

**Comment by mvllow** [comment]
The xresources if you don't mind. It doesn't look like we have a qt5 theme, we have a qterminal theme but I'm not too familiar with these tools 😭

**Comment by SarahAllenReed** [comment]
Done. Sorry for the delay, got caught up in job stuff.

And yeah, I'll send the qt5 theme once I have all three variants done and dusted. I had to port the main version so qt themes would play nice on my Pinephone, and I'm working on the other two before I send them your way. As you can see here, they're coming along half decently.

![image](https://user-images.githubusercontent.com/8343978/232874043-676ac476-3c0d-48ba-9d5e-2725485d9a23.png)

**Comment by mvllow** [comment]
Added qt5ct to our website. Feel free to open a new issue if you'd like to transfer your repo in :)
