### ISSUE TITLE
New theme for Geany

### ISSUE THREAD

**Issue by bonbuggie** [rose-pine/rose-pine-theme#106]
### Link to theme repo

https://github.com/bonbuggie/Geany-Rose-Pine-Moon-Theme

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

This was a reskin from another project, [Catppuccin for Geany](https://github.com/geany/geany)
Only includes the Rosé Pine **_Moon_** theme.

**Comment by bonbuggie** [comment]
I've accepted the invite and have imported the repository now.

**Comment by mvllow** [comment]
Grazie!
