### ISSUE TITLE
New theme for PureRef

### ISSUE THREAD

**Issue by bonbuggie** [rose-pine/rose-pine-theme#107]
### Link to theme repo

https://github.com/bonbuggie/PureRef

### What would you like to do with your repo?

Transfer my repo into the org

**Comment by mvllow** [comment]
Thanks for creating a new theme :)

Feel free to transfer your repo in, perhaps with the name "pure-ref"? Also, please add "theme" as a topic on the repository so it will be automatically added onto our site. I need to document this step somewhere 🙃

**Comment by bonbuggie** [comment]
Sorry about that! I've imported now and have included the theme topic this time.
