### ISSUE TITLE
New theme for polybar

### ISSUE THREAD

**Issue by RosieZiutka** [rose-pine/rose-pine-theme#111]
### Link to theme repo

https://github.com/RosieZiutka/rose-pine-polybar/tree/main

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

Theme i made for  polybar, I included all 3 variants.

**Comment by RosieZiutka** [comment]
Oh, i’m sorry i’m not exactly a markdown wizard 😅, and the preview images were done rather quickly, i will fix it in the morning. Thx for fast response.

**Comment by mvllow** [comment]
No worries! Once you transfer the repository I'm happy to make those changes as well :)

**Comment by RosieZiutka** [comment]
Sorry it have taken soooo long, i was bit busy and forogt about this, but it's transfered.
