### ISSUE TITLE
New theme for Btop

### ISSUE THREAD

**Issue by mrs4ndman** [rose-pine/rose-pine-theme#113]
### Link to theme repo

https://github.com/mrs4ndman/btop

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

Currently working on the tmux colorscheme, will finish it soon :)

It comes with the 3 variants + instructions

**Comment by mvllow** [comment]
Looking at the btop readme, it looks like their name is usually written as "btop" and not "Btop" if you don't mind changing the repo title/description. The theme looks lovely :) Feel free to transfer in any time!
