### ISSUE TITLE
New theme for Waybar

### ISSUE THREAD

**Issue by DankChoir** [rose-pine/rose-pine-theme#115]
### Link to theme repo

https://github.com/DankChoir/waybar-rosepine

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

A Rosé Pine theme ( more like a color extension) I made for Waybar, all 3 variants included. Please have a look ty.

**Comment by mvllow** [comment]
Invited to the org, feel free to transfer in :)

As far as the repository, please replace flavor/flavour in the readme/css files with variant. Thank you!

**Comment by DankChoir** [comment]
I had made the changes as suggested.

( I did not see the invitation tho, did it expire? 
And I have to manually transfer my repo to the org right? 
Sorry this is my first time doing these)

**Comment by DankChoir** [comment]
Ah nvm, i saw the the invitation. my bad
