### ISSUE TITLE
New theme for pywal

### ISSUE THREAD

**Issue by jrc03c** [rose-pine/rose-pine-theme#116]
Hi! I made a theme for pywal and I'd like to add it to the site, preferably as an official repo / theme. What's the next step? The repo is [here](https://github.com/jrc03c/pywal). Thanks!

**Comment by mvllow** [comment]
Did you need any help moving this into the org? If you don't have time I'm happy to fork it into the org and add you as a maintainer if that's easier. Let me know :)

**Comment by jrc03c** [comment]
Oh, so sorry! I completely forgot about this. Can you remind me what needs to be done?

**Comment by jrc03c** [comment]
Also: if it's easier for you to fork it and add me as a maintainer, that's totally fine with me!

**Comment by mvllow** [comment]
Looks like you're already in the org so it should let you transfer the repository into Rosé Pine within your repo settings

**Comment by mvllow** [comment]
Looks good, thank you!
