### ISSUE TITLE
New theme for Mona for Mastodon

### ISSUE THREAD

**Issue by SocietasEvanescentes** [rose-pine/rose-pine-theme#118]
### Link to theme repo

https://github.com/SocietasEvanescentes/RosePineForMona

### What would you like to do with your repo?

Keep my repo under my personal account

### Additional information

Hello! Please do inform me if the color palette is incorrect, this is my first time contributing to a major project, so I apologize if it/they don't follow 100 percent. It will be improved upon feedback. 

Screenshots can be found in the folder of “Moon” and “Dawn”.

**Comment by SocietasEvanescentes** [comment]
Here are images of the editor:

![IMG_6096](https://github.com/rose-pine/rose-pine-theme/assets/25782090/ce661169-74f6-4591-998e-1bc7485902a7)
![IMG_6103](https://github.com/rose-pine/rose-pine-theme/assets/25782090/df9530ac-c78d-4c65-b36e-626a8d56499f)

**Comment by ThatOneCalculator** [comment]
There's already a Mona theme: https://github.com/rose-pine/mona

**Comment by SocietasEvanescentes** [comment]
> There's already a Mona theme: https://github.com/rose-pine/mona

Interesting. I went to the website (rosepinetheme) and searched before, and it wasn't there, but now that you've pointed it out, it is… 

I think we could merge them; that creator only did the base Rose Pine theme, whereas I have done the Dawn and Moon theme. This would complete the trio.

**Comment by ThatOneCalculator** [comment]
In that case, I'd recommend instead submitting a pull request to that repo.

**Comment by SocietasEvanescentes** [comment]
> In that case, I'd recommend instead submitting a pull request to that repo.

I apologize for my naivety. When doing so, what do I do? When clicking it, it just shows branches, but no clear way for me to link. 

(I've really ever only used GitHub to create issues, my own projects, so PR is new to me. Thanks 😅)

**Comment by ThatOneCalculator** [comment]
Create a fork of the repo, add your changes to your fork, and then a "submit pull request" button will show up

**Comment by SocietasEvanescentes** [comment]
> Create a fork of the repo, add your changes to your fork, and then a "submit pull request" button will show up

Okay, I think I did it: https://github.com/rose-pine/mona/pull/1

**Comment by mvllow** [comment]
Closing in favour of the pull request. Thanks!
