### ISSUE TITLE
New theme for Github

### ISSUE THREAD

**Issue by jorismertz** [rose-pine/rose-pine-theme#121]
### Link to theme repo

https://github.com/jorismertz/github

### What would you like to do with your repo?

Transfer my repo into the org

**Comment by mvllow** [comment]
Thank you for the new theme!

I'd like to create a more general-purpose UserStyles repository and then move this into there. I'll reach back out here once I make that new repo :)

**Comment by jorismertz** [comment]
I just opened a pull request, when I find the time I'll add some instructions to the main readme file :)
