### ISSUE TITLE
New theme for Linear

### ISSUE THREAD

**Issue by LopeAriyo** [rose-pine/rose-pine-theme#127]
### Link to theme repo

https://github.com/LopeAriyo/linear

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

I've also open a [PR](https://github.com/alii/linear-style/pull/74) in Linear's style library so that the hex codes can be copied/searched from https://linear.style/

**Comment by mvllow** [comment]
Thank you for the new theme! Usually we don't have the header image in the readme (above "Usage") as it does take some time to load but definitely use that as the meta image in the repo settings.

Feel free to transfer in whenever :)

**Comment by LopeAriyo** [comment]
I'll make those changes now, thanks :D

I've initiated the transfer
