### ISSUE TITLE
New theme for RStudio

### ISSUE THREAD

**Issue by wujackwill** [rose-pine/rose-pine-theme#128]
### Link to theme repo

https://github.com/wujackwill/RStudio

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

* I just use the .tmtheme file from https://github.com/rose-pine/sublime-text, so thanks to ThatOneCalculator
* Todo: add more themes and improve the themes

**Comment by mvllow** [comment]
Thanks for the new theme! Invited to the org, transfer whenever you'd like.

**Repo feedback**

We should include minimal usage instructions, even if linking to the post with instructions. Perhaps something like:

1. Navigate to Tools &rarr; Global Options...
2. In Appearance, add your downloaded theme files
3. Select your preferred variant

Also feel free to add your name to the Thanks to section :)

**Comment by wujackwill** [comment]
Ok, I got it and thanks for the detailed instuctions. :)
