### ISSUE TITLE
Vim Colorscheme

### ISSUE THREAD

**Issue by iandwelker** [rose-pine/rose-pine-theme#13]
I made a colorscheme using Rosé Pine for Vim [here](https://github.com/iandwelker/rose-pine-vim). Would it be possible to get this featured here? Also, are there any changes that need to be made on my colorscheme or repo?

**Comment by ThatOneCalculator** [comment]
The color scheme looks fine, but you're going to have to follow the [Rosé Pine Template](https://github.com/rose-pine/rose-pine-template).

**Comment by mvllow** [comment]
We added an unofficial section in the readme, thank you! 🥰

Will reopen if you're wanting to transfer it to the org
