### ISSUE TITLE
New theme for qBittorrent

### ISSUE THREAD

**Issue by jorismertz** [rose-pine/rose-pine-theme#132]
### Link to theme repo

https://github.com/jorismertz/qbittorrent

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

I'm already in the org, just wanted to make sure it's okay to transfer

**Comment by mvllow** [comment]
Thanks for checking, sure thing! Feel free to transfer any time :)

**Comment by jorismertz** [comment]
It's transferred, thanks for the awesome theme btw!
