### ISSUE TITLE
New theme for Starship

### ISSUE THREAD

**Issue by JTrenerry** [rose-pine/rose-pine-theme#134]
### Link to theme repo

https://github.com/JTrenerry/Starship

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

The dawn theme kinda eh, but uses the same colours as the other two i.e. both using overlay etc.

First time doing something like this but I use rose pine moon for literally everything and since I was making a starship prompt might as well put it here in case someone may want to use in the future

**Comment by JTrenerry** [comment]
forgot to mention about it's literally just the prompt, the background of the terminal was just changing kitty theme.

**Comment by mvllow** [comment]
Love the flowers in the prompt :)

I invited you to the org. Please lowercase the repo name when transferring in. And in the readme, would you mind bolding the gallery headings, e.g.:

```diff
- Rosé Pine:
+ **Rosé Pine**
```

Thank you for the new theme 💜

**Comment by JTrenerry** [comment]
Should be done, thank you!
