### ISSUE TITLE
Theme request for delta

### ISSUE THREAD

**Issue by tgy** [rose-pine/rose-pine-theme#136]
### Link to app

https://github.com/dandavison/delta

### Would you be willing to work on this?

- [ ] Sure

### What is your favourite Rosé Pine accent

None

### Additional information

Delta is an awesome git diff tool, allowing for a very easy visualisation of actual code changes. Would be nice to support it with Rosé Pine :)

**Comment by ThatOneCalculator** [comment]
What you want is a [bat](https://github.com/sharkdp/bat) theme, which in turn is actually a legacy Sublime Text theme.

**Comment by mvllow** [comment]
For future visitors, we have an [example with bat](https://github.com/rose-pine/tm-theme?tab=readme-ov-file#example-sharkdpbat). Perhaps the discoverability could be improved.
