### ISSUE TITLE
New theme for Obsidian

### ISSUE THREAD

**Issue by JTrenerry** [rose-pine/rose-pine-theme#137]
### Link to theme repo

https://github.com/JTrenerry/obsidian

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

The current one is good, but some of it is kind of ugly in particular the buttons in the settings page (This is pretty much just changing that and a few other things to better align with some of the other themes as well as only using rose pine colours). It is also does not support other colour themes, and hasn't been updated in a couple years although there have been a couple issues on the repo.

This is not done yet, mainly just the readme but I think with time differences it should be okay.

**Comment by JTrenerry** [comment]
Now also allows users to select which theme / accent colour to use.

**Comment by mvllow** [comment]
Thank you for working on this, I'm curious if @mimishahzad has any thoughts—a PR to the existing repo could be beneficial if they'd be willing to transfer their repo into the org and have both of you as maintainers.

Otherwise, I'll review your repo when I have some free time and we can get it transferred in :)

**Comment by mimishahzad** [comment]
I'm good with that! Feel free to integrate it into anything sorry I lost track of this 😅

**Comment by JTrenerry** [comment]
More than happy for that, also saves me time getting an obsidian PR in, as we should be able to adjust the github repo value a lot easier than adding a whole new one.

**Comment by JTrenerry** [comment]
@mimishahzad @mvllow any update on transferring the repo into the org?

**Comment by ThatOneCalculator** [comment]
I thought we agreed on a PR into the existing repo?

**Comment by JTrenerry** [comment]
"a PR to the existing repo could be beneficial if they'd be willing to transfer their repo into the org"

I would prefer this.

**Comment by ThatOneCalculator** [comment]
Ah. Well, then that's up to the original author, I haven't reached out to them, pinging @mvllow

**Comment by mvllow** [comment]
Their repo has been forked into our org and I invited both Mimi and Jackson as maintainers. Go wild :)

**Comment by JTrenerry** [comment]
@mvllow Hey, just realised from someone on discord that the issues page is turned off, can you turn it on if possible.


Cheers.

**Comment by mvllow** [comment]
@JTrenerry done :)

**Comment by JTrenerry** [comment]
@mvllow can you give me permisisons to add issue templates to the repo, or I can dm the template on discord. Just want people to always have screenshots as there are way too many plugins haha.

**Comment by mvllow** [comment]
@JTrenerry do you mean the Obsidian repo? I made you an admin but believe you should already be able to make a file like https://github.com/rose-pine/neovim/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml or similar. Hope that helps :)

**Comment by JTrenerry** [comment]
thank you, forgot you can just chuck the file in that way
