### ISSUE TITLE
New theme: mako

### ISSUE THREAD

**Issue by stanekondrej** [rose-pine/rose-pine-theme#139]
can be found at https://github.com/stanekondrej/mako

hope I'm doing this right 😄

**Comment by mvllow** [comment]
Looks good! Assuming you want to transfer it in, I invited you to the org so feel free to do so at any time. Only feedback for the repo itself is to consider removing the images folder in favour of inlining them into the readmd (via the GitHub CDN or similar) to avoid having to downloading images when cloning :)

**Comment by stanekondrej** [comment]
OK, I inlined the images in the readme. Transferring into the org now, and closing this. Thanks for your time ❤️
