### ISSUE TITLE
New theme for Zen Browser

### ISSUE THREAD

**Issue by wzykubek** [rose-pine/rose-pine-theme#140]
### Link to theme repo

https://github.com/wzykubek/zen-rose-pine

### What would you like to do with your repo?

Transfer my repo into the org

**Comment by mvllow** [comment]
Thank you! Please rename the repo to `zen-browser` during transfer :)

Also, if you could, use the GitHub CDN or similar to inline the images so we can remove the "assets" folder and reduce clone size.

**Comment by wzykubek** [comment]
Done :)
