### ISSUE TITLE
Add RGB colors to palette

### ISSUE THREAD

**Issue by rapha8l** [rose-pine/rose-pine-theme#30]
Hi
Could you provide RGB colors for all your palettes ?
I specially like the dawn one
thanks  

Raphael

**Comment by mvllow** [comment]
Thanks for the suggestion, we'll get those listed in rgb asap :) 

You may already know but we do have the hex values on https://mellow.dev/rose-pine

**Comment by rapha8l** [comment]
Thanks !

**Comment by Jimmysit0** [comment]
I'll work on that today

**Comment by Jimmysit0** [comment]
Sorry for the delayed response, I'll work on it and I'll send a message to @mvllow with the rgb values, so I guess it's time to close the issue : )

**Comment by Jimmysit0** [comment]
Rosé pine: 
R:  25, G:  23, B:  36 | Hex: #191724
R:  31, G:  29, B:  46 | Hex: #1F1D2E
R:  38, G:  35, B:  58 | Hex: #26233A
R:  85, G:  81, B: 105 | Hex: #555169
R: 110, G: 106, B: 134 | Hex: #6E6A86
R: 224, G: 222, B: 244 | Hex: #E0DEF4
R: 235, G: 111, B: 146 | Hex: #EB6F92
R: 246, G: 193, B: 119 | Hex: #F6C177
R: 235, G: 188, B: 186 | Hex: #EBBCBA
R:  49, G: 116, B: 143 | Hex: #31748F
R: 156, G: 207, B: 216 | Hex: #9CCFD8
R: 196, G: 167, B: 231 | Hex: #C4A7E7

Rosé pine moon: 
R:  35, G:  33, B:  54 | Hex: #232136
R:  42, G:  39, B:  63 | Hex: #2A273F
R:  57, G:  53, B:  82 | Hex: #393552
R:  89, G:  84, B: 109 | Hex: #59546D
R: 129, G: 124, B: 156 | Hex: #817C9C
R: 224, G: 222, B: 244 | Hex: #E0DEF4
R: 235, G: 111, B: 146 | Hex: #EB6F92
R: 246, G: 193, B: 119 | Hex: #F6C177
R: 234, G: 154, B: 151 | Hex: #EA9A97
R:  62, G: 143, B: 176 | Hex: #3E8FB0
R: 156, G: 207, B: 216 | Hex: #9CCFD8
R: 196, G: 167, B: 231 | Hex: #C4A7E7

Rosé pine dawn: 
R: 250, G: 244, B: 237 | Hex: #FAF4ED
R: 255, G: 250, B: 243 | Hex: #FFFAF3
R: 242, G: 233, B: 222 | Hex: #F2E9DE
R: 152, G: 147, B: 165 | Hex: #9893A5
R: 110, G: 106, B: 134 | Hex: #6E6A86
R:  87, G:  82, B: 121 | Hex: #575279
R: 180, G:  99, B: 122 | Hex: #B4637A
R: 234, G: 157, B:  52 | Hex: #EA9D34
R: 215, G: 130, B: 126 | Hex: #D7827E
R:  40, G: 105, B: 131 | Hex: #286983
R:  86, G: 148, B: 159 | Hex: #56949F
R: 144, G: 122, B: 169 | Hex: #907AA9

**Comment by mvllow** [comment]
Thank you 🙏 

I'll get these on the website soon

**Comment by ThatOneCalculator** [comment]
> Thank you 🙏 
> 
> I'll get these on the website soon

I could never tell, is 🙏 supposed to be a high five or praying hands? 🤔

**Comment by mvllow** [comment]
> I could never tell, is 🙏 supposed to be a high five or praying hands? 🤔

A salute of gratitude 😌

**Comment by rapha8l** [comment]
Thanks a lot !
