### ISSUE TITLE
Rose Pine Vim

### ISSUE THREAD

**Issue by co1ncidence** [rose-pine/rose-pine-theme#31]
I [mek theem](https://gitlab.com/co1ncidence/rose-pine). The current rose pine vim theme is meh so I made my own. I don't use github anymore so I didn't PR as idk how you would integrate it into your repo (which you don't have to as this theme *is* mostly based off my own preferences in a vim theme).

![screen shot](https://gitlab.com/co1ncidence/rose-pine/-/raw/master/scr/dark.png)

Also, thanks for starring mountaineer, I'm a massive fan of yours so it means a lot lol.

**Comment by mvllow** [comment]
We'll mention your theme in the readme, thank you so much!

I personally don't know much about theming vim but is that a lightline/airline theme in the screenshot & is that included? Looks lovely 🥰

**Comment by co1ncidence** [comment]
Not airline or lightline, it's a statusline made using default vimscript (I don't like using plugins when built in vim features will do just fine). [here it is](http://0x0.st/-8Ab.bin) if you want to try it out yourself, just source it using `source /path/to/file.vim` in your vim config. 

P.S. Change the filetype to `.vim` if it isn't already, my upload script is being annoying.
