### ISSUE TITLE
Base16 theme

### ISSUE THREAD

**Issue by TorchedSammy** [rose-pine/rose-pine-theme#34]
If Rose Pine had a base16 theme, this would make it way easier to apply the theme since something like [flavours](https://github.com/Misterio77/flavours) can do it in 1 command. People will also be able to use it for other programs that don't have  the theme done yet

This also means you don't have to make themes specifically for anything, unless there isn't a base16 template (eg GRUB)

**Comment by edunfelt** [comment]
I love base16, it's so useful, especially along with flavours! I could possibly work on this later today :)

**Comment by edunfelt** [comment]
For base16 themes ideally 16 colors would be needed to create a good color scheme. But over at https://mellow.dev/rose-pine I can only find 12 colors. Would it be possible to add a few additional colors as to create a well balanced scheme that can be used with base16 builders, @mvllow? 
Playing around with the existing colors, I also noticed that the contrast between the first three shades is quite low, both for Rosé Pine and for Rosé Pine Moon, making it difficult to apply to a more general setting such as described [here](https://github.com/chriskempson/base16/blob/master/styling.md).

**Comment by mvllow** [comment]
We are using a shadow color and three highlight colors in our vscode theme that are not on the website: https://github.com/rose-pine/vscode/blob/main/pinecone.config.js

Here's the relevant code pulled:

```js
uiShadow: {
  base: alpha('#010101', 0.1),
  moon: alpha('#191724', 0.3),
  dawn: alpha('#f2e9de', 0.3),
},

highlight: {
  base: alpha('#6e6a86', 0.2),
  moon: alpha('#817c9c', 0.15),
  dawn: alpha('#6e6a86', 0.08),
},

highlightInactive: {
  base: alpha('#6e6a86', 0.1),
  moon: alpha('#817c9c', 0.08),
  dawn: alpha('#6e6a86', 0.05),
},

highlightOverlay: {
  base: alpha('#6e6a86', 0.4),
  moon: alpha('#817c9c', 0.3),
  dawn: alpha('#6e6a86', 0.15),
},
```

Hope that helps, if there are tweaks needed let me know and I can look into it further :)

**Comment by edunfelt** [comment]
![test](https://user-images.githubusercontent.com/29271899/110852851-29625880-82b3-11eb-83aa-688f2628f36a.png)
Ok, so here is a first "draft" I guess of the Rosé Pine base16 theme. You can compare with the above linked styling guidelines what kind of element each color would typically correspond to. I tried to make sure the contrasts would be ok so hopefully it should be legible with the different fg/bg colors as well. Please, any and all feedback is appreciated! :)

**Comment by edunfelt** [comment]
I finished working on the schemes now, and opened a PR over at [the source repo](https://github.com/chriskempson/base16-schemes-source), seems like it could take a while though. Attached are the three themes as they look right now (regular, moon, dawn). 

![test](https://user-images.githubusercontent.com/29271899/110968706-240b1980-8358-11eb-9c47-251d3e89911d.png)
![test2](https://user-images.githubusercontent.com/29271899/110968710-24a3b000-8358-11eb-812c-d733702db3db.png)
![test3](https://user-images.githubusercontent.com/29271899/110968711-253c4680-8358-11eb-85f9-a5ddfdad8bd6.png)

**Comment by edunfelt** [comment]
Hi again,
The PR has now been merged and the scheme is added to the list at the [base16 repo](https://github.com/chriskempson/base16#scheme-repositories). Feel free to add the scheme repo to your list here and close this issue if you consider it finished. :sparkling_heart:

**Comment by TorchedSammy** [comment]
I think it should also say on this repo there's a base16 theme available

**Comment by mvllow** [comment]
Thank you so much @edunfelt and sorry we couldn't give more feedback - we are in the process of moving and it's been a lil crazy 🙃

I will add a link in the main repo to this
