### ISSUE TITLE
Emacs theme link not working.

### ISSUE THREAD

**Issue by Ultra-Hax** [rose-pine/rose-pine-theme#35]
https://github.com/caelie/rose-pine-emacs gives you error 404.

**Comment by mvllow** [comment]
Oh no! Looks like they may have changed their username or deleted their account. Any idea @ThatOneCalculator or @Jimmysit0? With caelie's permission we can try to get the theme in the org

**Comment by ThatOneCalculator** [comment]
Idk, I don't use emacs. Probably jimmy.

**Comment by Jimmysit0** [comment]
Cae deleted their email, stopped using discord and basically isn't using emacs anymore... I do have the dawn version, but not the other ones, not sure what can we do, I was looking for them too...

**Comment by Jimmysit0** [comment]
From what I can see, @Ultra-Hax requested adding rosé pine to doom emacs, sadly if we can't find the emacs repo, most likely we're not getting those into doom

**Comment by thegeorgeous** [comment]
@Jimmysit0 @ThatOneCalculator @Ultra-Hax I found this repo that has the theme 
https://github.com/thongpv87/rose-pine-emacs

**Comment by Jimmysit0** [comment]
That's really cool! I'll talk with the org members asap.
