### ISSUE TITLE
SVG Rose icons

### ISSUE THREAD

**Issue by ng-hai** [rose-pine/rose-pine-theme#38]
Hi @mvllow, where can I get this rose icon in SVG format, for each theme variant?

https://raw.githubusercontent.com/rose-pine/rose-pine-theme/main/assets/icon.png

**Comment by ThatOneCalculator** [comment]
I mean you can always just color pick for the BG, it's a super simple svg

**Comment by mvllow** [comment]
@ThatOneCalculator we actually didn't have official moon/dawn ones, but now they should all be unified.

The logo palette now actually uses our colors, eg. `base`, `pine`, `pine 50%` and `rose`

**Comment by ThatOneCalculator** [comment]
Nice
