### ISSUE TITLE
Add something to spicetify-themes

### ISSUE THREAD

**Issue by Milo123459** [rose-pine/rose-pine-theme#41]
Add a rose pine to a) the master branch (outdated spotify) and b) the v2 branch (the updated spotify)

Link for spiectify-themes: https://github.com/morpheusthewhite/spicetify-themes

**Comment by mvllow** [comment]
PR's all always welcome 😌

**Comment by Milo123459** [comment]
Hahah, I meant into the spicetify-themes repo, and I tried. It's harder then it looks.

**Comment by nicoleajoy** [comment]
Hello! I've taken on the task to add Rose Pine to Spicetify (at least for one theme). @Milo123459 was right, it was a lot of trial and error! Here's what it currently looks like:

### Theme: Ziro

#### Color Scheme: Rose Pine Dawn

![rose-pine-dawn](https://user-images.githubusercontent.com/36486525/162630688-6a215266-5364-436b-a9a0-f59f7e0eda27.jpg)

#### Color Scheme: Rose Pine Moon

![rose-pine-moon](https://user-images.githubusercontent.com/36486525/162630694-3ad556b7-9ab3-4ad2-a3e1-d1247f5fd09b.jpg)

While we wait for the [PR](https://github.com/spicetify/spicetify-themes/pull/716) to be reviewed, I'll work on another set for Dribblish (one of the bigger Spicetify themes). Please me know if you have any suggestions for improvements!

**Comment by mvllow** [comment]
thank you for taking this on, that looks great 💜

once merged, we may want to create a repo (either in the org or your personal) with our template and usage instructions so we can then point to that from the site 😌

**Comment by nicoleajoy** [comment]
I'm happy to hear that! And thank you for linking the example, I'll make sure to create the repo as well. :)

**Comment by Milo123459** [comment]
Looks absolutely amazing! Well done & thanks!

**Comment by mvllow** [comment]
Forgive my ignorance as far as spicetify, but because https://github.com/spicetify/spicetify-themes/pull/716 was merged is this good to close?

**Comment by ThatOneCalculator** [comment]
looks like it
