### ISSUE TITLE
[Request] IntelliJ theme

### ISSUE THREAD

**Issue by mvllow** [rose-pine/rose-pine-theme#49]
https://www.jetbrains.com/help/idea/user-interface-themes.html

**Comment by Stegnerd** [comment]
I just started working on this! This is my first intellij plugin but I love this theme and want it in my ide too 😃 . I do have a simple question though. Where do I submit the pr to when I am ready?

**Comment by mvllow** [comment]
Yay! A good first step would be to PR this repo and add your theme to the readme. If you'd like to transfer the repo to the Rosé Pine org and be a maintainer there, please use [our template](https://github.com/rose-pine/rose-pine-template).

However you wish to proceed, we thank you in advance for tackling this 🥰

**Comment by Jmorjsm** [comment]
I also took a stab at this today: https://github.com/Jmorjsm/rose-pine-intellij
The published plugin is awaiting moderation [here](https://plugins.jetbrains.com/plugin/18141-rose-pine-intellij).

Happy to add this to the readme in this repo or await @Stegnerd as he claimed this first 🙂

**Comment by Stegnerd** [comment]
@Jmorjsm your's looks way better than mine! you should totally go ahead, and you did it faster than me too 😉 good job!

**Comment by mvllow** [comment]
Closed by https://github.com/rose-pine/rose-pine-theme/pull/58

Thanks!
