### ISSUE TITLE
RGB and HSL values not accurate?

### ISSUE THREAD

**Issue by mcchrish** [rose-pine/rose-pine-theme#50]
## Official website
<img width="601" alt="Screen Shot 2021-10-04 at 9 57 19 AM" src="https://user-images.githubusercontent.com/7200153/135782927-5183c73b-e0fe-4d6a-a8f2-b8acd4d15939.png">

## Google search
<img width="700" alt="Screen Shot 2021-10-04 at 9 57 34 AM" src="https://user-images.githubusercontent.com/7200153/135782933-63998cc8-02d8-4a7b-b0de-ae1ae0615ee9.png">

## System color picker (macos)
<img width="258" alt="Screen Shot 2021-10-04 at 9 59 49 AM" src="https://user-images.githubusercontent.com/7200153/135783020-03c1c35d-4f35-48d8-812f-a47204a73283.png">

**Comment by mvllow** [comment]
Good catch! We're using [color convert](https://www.npmjs.com/package/color-convert) and may be handling rounding incorrectly?

I'd gladly accept a PR to fix our conversions, otherwise I may just go in and hardcode the correct values since our palette shouldn't be changing 😌

**Comment by mvllow** [comment]
closed with the launch of https://github.com/rose-pine/rose-pine-site
