### ISSUE TITLE
[Request] KDE theme

### ISSUE THREAD

**Issue by maybork** [rose-pine/rose-pine-theme#64]
Hi, I really love the theme and would enjoy using it in KDE a ton. I understand if that's possible/difficult, but are there reasons that out of most major DEs KDE isn't included? I'd love to work on this and you'll likely see a PR from me in a couple of days once I wrap my head around the concepts, but I'd be more than happy to collaborate on it with someone more experienced!

**Comment by ThatOneCalculator** [comment]
> Hi, I really love the theme and would enjoy using it in KDE a ton. I understand if that's possible/difficult, but are there reasons that out of most major DEs KDE isn't included? I'd love to work on this and you'll likely see a PR from me in a couple of days once I wrap my head around the concepts, but I'd be more than happy to collaborate on it with someone more experienced!

As for a reason, nobody on our team uses KDE Plasma nor has ever made themes for it. We can try!

**Comment by ThatOneCalculator** [comment]
Wait, I completely forgot this exists lol: https://github.com/maybork/kde
