### ISSUE TITLE
Missing jump links

### ISSUE THREAD

**Issue by YangFong** [rose-pine/rose-pine-theme#66]
![image](https://user-images.githubusercontent.com/70502828/147847977-8bd9a969-44b9-4f94-ab0c-5d3be9ad7d51.png)

**Comment by mvllow** [comment]
related https://github.com/rose-pine/rose-pine-theme/issues/55

**Comment by mvllow** [comment]
closed with the launch of https://github.com/rose-pine/rose-pine-site
