### ISSUE TITLE
wallpaper generator

### ISSUE THREAD

**Issue by chunghha** [rose-pine/rose-pine-theme#72]
I've just simply written https://github.com/chunghha/go-rosepine-genart to generate few wallpapers with rose_pine theme colors for myself. If someone sees it's useful then I will open a PR to include it to the site.

for example, rose_pine_maze.png looks like, 
<img width="774" alt="Screen Shot 2022-04-03 at 9 14 52 PM" src="https://user-images.githubusercontent.com/24458075/161463017-65579295-3c28-47a9-9299-3bf233239636.png">

cc @mvllow

**Comment by ThatOneCalculator** [comment]
We already have a wallpapers repo, but I think it'd be a great addition to that!

Also, looks like you forgot to change this part :stuck_out_tongue: 

![image](https://user-images.githubusercontent.com/44733677/161463876-0d19357a-c7a8-4783-bc60-dca0462a3572.png)

**Comment by ThatOneCalculator** [comment]
https://github.com/rose-pine/wallpapers @chunghha

**Comment by mvllow** [comment]
that wallpaper makes my brain hurt, i love it 💜

sounds like the tool would generate a unique wallpapers each time so maybe we need a resources category – similar to https://github.com/fvrests/rose-pine-images which is not yet mentioned on our site either

**Comment by mvllow** [comment]
closing in favour of https://github.com/rose-pine/rose-pine-site/issues/48 😌
