### ISSUE TITLE
Add terminal ports to iTerm2-Color-Schemes

### ISSUE THREAD

**Issue by mvllow** [rose-pine/rose-pine-theme#74]
Looks like these will be bundled into WezTerm one day, could be a good idea to polish up all of our terminal themes and try pull requesting the repo 😌 

Suggested here: https://twitter.com/wezfurlong/status/1514375897528381440?s=20
Repo: https://github.com/mbadolato/iTerm2-Color-Schemes

**Comment by mvllow** [comment]
Lovely! We'll close this once that PR is merged then, thanks :)

**Comment by prateektade** [comment]
The PR is merged! :grin:

I am also considering adding the themes to another huge terminal themes collection called [Gogh](https://github.com/Gogh-Co/Gogh). Will link the PR here once I create it.
