### ISSUE TITLE
New theme for GDevelop

### ISSUE THREAD

**Issue by EhanAhamed** [rose-pine/rose-pine-theme#77]
### Link to theme repo

https://github.com/rose-pine/GDevelop

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

I realize I should have made an issue before creating a new repo... oops 🤷

See [this pull request](https://github.com/4ian/GDevelop/pull/4079) in [GDevelop's repo](https://github.com/4ian/GDevelop/) for more info!

**Comment by mvllow** [comment]
No worries, an issue isn't necessary since you're in the org 😌 Create away!
