### ISSUE TITLE
New theme for Telegram iOS

### ISSUE THREAD

**Issue by asdreemurr844** [rose-pine/rose-pine-theme#79]
### Link to theme repo

https://github.com/asdreemurr844/rose-pine-telegram-ios

### What would you like to do with your repo?

Transfer my repo into the org

**Comment by asdreemurr844** [comment]
> Is there a reason it's iOS specific?

well... telegram clients do not have the same theme format (but essentially if i distribute the theme via a link i can port it to all other clients as well)

**Comment by ThatOneCalculator** [comment]
Ah, gotcha. If you could port it to others as well that'd be great so we could have it as just a "telegram" repo

**Comment by asdreemurr844** [comment]
> Ah, gotcha. If you could port it to others as well that'd be great so we could have it as just a "telegram" repo

hmm... In Dracula, in the repositories of themes for Telegram there are separate ones for iOS, Android and TDesktop...

**Comment by ThatOneCalculator** [comment]
We're not Dracula though :smile: 

I get the concern but I personally feel it'd be better under a unified repo.

**Comment by asdreemurr844** [comment]
> We're not Dracula though :smile: 
> 
> 
> 
> I get the concern but I personally feel it'd be better under a unified repo.

okay, if I have time, I will try to do a port to TDesktop and Android.

**Comment by mvllow** [comment]
we can do folders under the telegram repo for each platform :) i don't think it is necessarily a blocker though

**Comment by asdreemurr844** [comment]
oops, my githab account was linked to an old email account that I basically have no access to, and I forgot about it. is it possible to resend the invite?

**Comment by mvllow** [comment]
re-invited. you may have gotten two emails, the latest one should work :)

**Comment by asdreemurr844** [comment]
thanks!

**Comment by asdreemurr844** [comment]
I'm sorry, but...

I probably won't be able to do the port, since:

a)  ~~I have a lot of mental issues, no energy for it, plus college (or high school, not clear yet) and I'm a sea of problems~~ I'm lazy

b) there are some other reasons, but they are extremely personal, though maybe you can guess what they are by the fact that I'm writing this now after a year.

I'm sorry.

**Comment by mvllow** [comment]
No worries @asdreemurr844, hope all is well & thank you for the update!

I'll close this in case someone else wants to take it over (and create a new issue).
