### ISSUE TITLE
New theme for Black Box terminal

### ISSUE THREAD

**Issue by marcelovbcfilho** [rose-pine/rose-pine-theme#80]
### Link to theme repo

https://github.com/marcelovbcfilho/black-box

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

This theme was created following the already present pallet in the [gnome-terminal](https://github.com/rose-pine/gnome-terminal) official repository.

**Comment by mvllow** [comment]
Thanks for your contribution :) I'm out of town but we'll get this added to the org soon!
