### ISSUE TITLE
New theme for Discord Web

### ISSUE THREAD

**Issue by purr** [rose-pine/rose-pine-theme#82]
### Link to theme repo

https://github.com/purr/discord-web

### What would you like to do with your repo?

Duplicate (clone) my repo into the org

### Additional information

Yeah i have no clue, spent like a week on doing it, cuz wanted my whole linux to have same theme but i hate modded discords so i made this
pls feel free to edit some of the code out or to edit the readme, cuz idk, im not a professional and stuff
i only made rose pine moon because i like it more....sry x

**Comment by mvllow** [comment]
Thanks for working on this! I'm curious if this should be added the existing discord theme repo? Perhaps we can make subfolders: "desktop" & "web"

**Comment by ThatOneCalculator** [comment]
Actually the existing desktop theme should work on web, I'm unsure why there needs to be a separate web theme

**Comment by purr** [comment]
Yeah the repo is made for just modded discord iirc, so just making it to discord and adding both would be cool i guess

and to t1c's comment, the current theme for discord was/is outdated, it had a lot of stuff missing in my opinion, as u can see my css editing theres lot more like individual colors of buttons

**Comment by ThatOneCalculator** [comment]
IMO, your CSS should be PR'd into the discord repo.

**Comment by mvllow** [comment]
Closing in favour of a pull request to our existing theme.
