### ISSUE TITLE
New theme for Warp

### ISSUE THREAD

**Issue by yukkobay** [rose-pine/rose-pine-theme#83]
### Link to theme repo

https://github.com/yukkobay/warp

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

Warp is my favorite terminal app. 
https://www.warp.dev
https://github.com/warpdotdev/Warp

I made it based on other rose-pine theme repositories. Please give me feedback if you have any.

**Comment by mvllow** [comment]
Appreciate the new theme! Invited to org and I believe you will then be able to transfer it in :)

**Comment by yukkobay** [comment]
@mvllow Thank you for inviting to org!
However, it was too late to check and it has expired. I am so sorry. Could you invite me again?

**Comment by mvllow** [comment]
Done :)

**Comment by zoedsoupe** [comment]
what about this issue? I just built another repo for warp (didn't see this issue). We can move on this?

**Comment by mvllow** [comment]
@zoedsoupe I invited you to the org if you would like to add your repo :)

**Comment by mvllow** [comment]
Closing because we are currently linking to https://github.com/thanhsonng/rose-pine-warp on our website. Happy to revisit. Would be interested in getting an official version included in Warp by default 🤌
