### ISSUE TITLE
New theme for LXTerminal

### ISSUE THREAD

**Issue by prateektade** [rose-pine/rose-pine-theme#84]
### Link to theme repo

https://github.com/prateektade/rose-pine-lxterminal

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

[LXTerminal](https://github.com/lxde/lxterminal) is the default terminal emulator packaged with the lightweight desktop environment [LXDE](http://www.lxde.org/).

This repository contains configuration files for all 3 flavors - Rosé Pine, Rosé Pine Dawn and Rosé Pine Moon.

**Comment by mvllow** [comment]
Renamed, grazie 😌
