### ISSUE TITLE
New theme for QTerminal

### ISSUE THREAD

**Issue by prateektade** [rose-pine/rose-pine-theme#85]
### Link to theme repo

https://github.com/prateektade/rose-pine-qterminal

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

[QTerminal](https://github.com/lxqt/qterminal) is the default terminal emulator for the LXQt desktop.

**Comment by mvllow** [comment]
Looks good! Feel free to rename the repo and transfer in :)
