### ISSUE TITLE
New theme for Browser extension Vimium C

### ISSUE THREAD

**Issue by zxx-457** [rose-pine/rose-pine-theme#86]
### Link to theme repo

https://github.com/zxx-457/rose-pine-vimiumc

### What would you like to do with your repo?

Transfer my repo into the org

**Comment by mvllow** [comment]
Thanks for the new theme! Let me know if you have any troubles transferring in or need a new org invite :)

**Comment by zxx-457** [comment]
> Thanks for the new theme! Let me know if you have any troubles transferring in :)

I'm sorry .  

Now it's done ! THank you !
