### ISSUE TITLE
New theme for Xresources

### ISSUE THREAD

**Issue by harishnkr** [rose-pine/rose-pine-theme#90]
### Link to theme repo

https://github.com/harishnkr/xresources

### What would you like to do with your repo?

Transfer my repo into the org

**Comment by mvllow** [comment]
Looks great, thank you for making this :)

**Comment by harishnkr** [comment]
Thanks. It's been my pleasure.

**Comment by harishnkr** [comment]
Repo moved over to https://github.com/rose-pine/xresources

Closing the issue
