### ISSUE TITLE
Theme request for tmux

### ISSUE THREAD

**Issue by honocoder** [rose-pine/rose-pine-theme#92]
### Link to app

https://github.com/tmux/tmux/wiki

### Would you be willing to work on this?

- [ ] Sure

### What is your favourite Rosé Pine accent

None

### Additional information

It would be nice to have a tmux theme to be consistent with iTerm and Neovim as it is a common set.

**Comment by mvllow** [comment]
I looked at https://github.com/dracula/tmux for inspiration and there's a lot going on – I don't personally use tmux so am not too confident in theming it.

If anyone has a simple example for a tmux theme please share :)

**Comment by thuanowa** [comment]
# my personal config

## Preview
![image](https://user-images.githubusercontent.com/40050527/216932161-dfabcfd6-b719-4ad5-9856-7d6b89213988.png)

> using kitty rose pine dawn

## Rose pine dawn
```bash
set -g status-interval 1
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g status-position top
set -g default-terminal "tmux"
set -g status-left '#[fg="#575279"]#[bold]#{s/root//:client_key_table} '

set -g status-right-length 85
set -g status-right '#[fg="#575279"]#[bold] [ #S ]'
set -g status-style fg='#575279'
set -g window-status-current-style fg='#575279',bold
set -g pane-border-style fg='#575279'
set -g pane-active-border-style fg='#575279'
set -g display-panes-active-colour '#575279'
set -g display-panes-colour '#fffaf3'
set -g clock-mode-colour '#575279'
set -g mode-style fg='#575279',bg='#d7827e'
set -g message-style fg='#575279',bg='#fffaf3'
```

###### dotfiles: https://github.com/thuanowa/dotfiles

**Comment by mvllow** [comment]
For those looking: https://github.com/rose-pine/tmux
