### ISSUE TITLE
New theme for Surfingkeys

### ISSUE THREAD

**Issue by thuanowa** [rose-pine/rose-pine-theme#95]
### Link to theme repo

https://github.com/thuanowa/surfingkeys/

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

#94

**Comment by mvllow** [comment]
Thanks for adding this! Please rename "App" in the readme to "Surfingkeys" as well as updating the repo description in the side bar :)

I'll send an org invite and feel free to transfer in!

Small nitpick with the structure: If it doesn't break anything, are you able to inline the images in the readme? E.g. dragging an image into the readme on GitHub will create a CDN link so when people clone the repo they don't have to pull down all the images too.

**Comment by thuanowa** [comment]
https://github.com/thuanowa/surfingkeys/issues/7

**Comment by thuanowa** [comment]
https://github.com/rose-pine/surfingkeys
