### ISSUE TITLE
New theme for Zellij

### ISSUE THREAD

**Issue by anihm136** [rose-pine/rose-pine-theme#96]
### Link to theme repo

https://github.com/anihm136/zellij

### What would you like to do with your repo?

Transfer my repo into the org

**Comment by mvllow** [comment]
Invited, feel free to transfer in :)

Great timing too, just learned about zellij yesterday. Thank you!

**Comment by anihm136** [comment]
Done! I'm also a new convert (both to rose-pine and zellij), so it was a fun experience porting the theme!
