### ISSUE TITLE
New theme for Hyprland

### ISSUE THREAD

**Issue by jishnurajendran** [rose-pine/rose-pine-theme#98]
### Link to theme repo

https://github.com/jishnurajendran/hyprland-rosepine

### What would you like to do with your repo?

Transfer my repo into the org

### Additional information

A Rose pine touch to Hyprland. 

[https://hyprland.org/](https://hyprland.org/)
[https://github.com/hyprwm/Hyprland](https://github.com/hyprwm/Hyprland)

Three flavors of Rose-Pine are included according to the color pallet. Any feedback will be much appreciated.

**Comment by mvllow** [comment]
Apologies for the delay, thank you for the new theme!

**Comment by jishnurajendran** [comment]
Thanks for the feedback. I have renamed the conf files.
